### PR TITLE
Avoid duplication between README and CONTRIBUTING

### PR DESCRIPTION
**Pull request by elemoine**
It took me some time to find how to run a specific spec. This PR suggests to add a note to the README.md file about that.

### CODE REVIEW

**Comment by elemoine** [comment]
The build fails on Travis, but it looks like that's unrelated to this patch.

**Comment by rnelson0** [comment]
The typical method to run an individual test is 'bundle exec rspec <file>'

**Comment by elemoine** [comment]
> The typical method to run an individual test is 'bundle exec rspec '

Could you please provide the full command line (for example for the spec file I used as an example in my patch)?

`bundle exec rspec spec/defines/collectd_plugin_python_module_spec.rb` does not work for me.

**Comment by igalic** [comment]
@elemoine i'd preffer this was pushed to @voxpupuli / module_sync

**Comment by elemoine** [comment]
> the method how to run individual spec tests should already be documented in CONTRIBUTING.md

I missed it, and got confused by the fact that the README file also includes indications on how to run the tests.

Feel free to close that PR.

**Comment by igalic** [comment]
@elemoine if you modify it to actually remove all of that duplication, and instead just tell people to look into CONTRIBUTING.md that would be great!

**Comment by elemoine** [comment]
Makes sense. Will do.

**Comment by igalic** [comment]
thank you @elemoine!

**Comment by rnelson0** [comment]
@elemoine Sorry, was on a phone and couldn't type right. `bundle exec rake spec_prep` will download the fixtures, then you can test individual files via `bundle exec rspec spec/defines/collectd_plugin_python_module_spec.rb` or similar.

**Comment by elemoine** [comment]
Branch updated as discussed. I also changed the PR title.

**Comment by jyaworski** [comment]
@elemoine can you look into basing this against https://github.com/voxpupuli/modulesync_config/blob/master/moduleroot/CONTRIBUTING.md instead? Most of these modules use that.

**Comment by elemoine** [comment]
Could you please provide more details?  I don't fully understand what you expect, and I'd like to avoid doing something that doesn't match the developers' expectations. Thanks.

**Comment by jyaworski** [comment]
Lots of the modules in the voxpupuli organization (like this one) are under the control of modulesync. We share a few files across our modules, one being CONTRIBUTING.md. If you modify the CONTRIBUTING.md I linked, it will get synced to all of our modules.

**Comment by jyaworski** [comment]
Hello: see https://github.com/voxpupuli/modulesync_config/pull/63

The README changes are OK. @igalic should we have some way to append to contributing in .sync.yml? Or is that stupid?

**Comment by jyaworski** [comment]
@elemoine is this still needed?

Can it be rebased?

**Comment by elemoine** [comment]
> @elemoine is this still needed?
> 
> Can it be rebased?

Feel free to close this if this is not needed anymore.

**Comment by nibalizer** [comment]
@elemoine it is in merge-conflict. Can you update it?

**Comment by jyaworski** [comment]
Closing due to lack of response.

**Pull request closed without merging**
