### PR TITLE
Fix type mismatch for ovs_stats port

### PR DESCRIPTION
**Pull request by mrunge**
#### Pull Request (PR) description

There is a typo in the template to create the ovs_stats config. For collectd, the given port number is a string, where
puppet-collectd treats this as a port, thus resulting as a number in the collectd config file.
Since collectd upstream uses 6640 by default, this option is rarely required.

#### This Pull Request (PR) fixes the following issues
Fixes: #958

### CODE REVIEW

**Comment by bastelfreak** [comment]
@mrunge can you take a look at the failing unit tests and maybe add an acceptance test for this change? We've a bunch of examples at https://github.com/voxpupuli/puppet-collectd/tree/master/spec/acceptance

**Comment by mrunge** [comment]
Thank you for your quick look.

The failing tests lead me to the acceptance tests. If the tests are passing now, this should be good to go :)

**Comment by mrunge** [comment]
Okay, tests pass now and the tests also check for existence of quotation marks.

**Comment by bastelfreak** [comment]
can you please add an acceptance test for this as well? :)

**Comment by mrunge** [comment]
Tests fail with:
 E: Unable to locate package collectd-ovs-stats on ubuntu

**Comment by mrunge** [comment]
The package is not available on ubuntu and debian (which uses the same repo); it also fails to load on centos either.
There is not much value in adding a test, when the infra can not check it properly.

**Comment by mrunge** [comment]
@bastelfreak any opinion to move forward here?

**Pull request merged**
