### PR TITLE
collectd < 5.5 doesn't come with mysql InnodbStats.

### PR DESCRIPTION
**Pull request by bzed**
The InnodbStats option of the mysql plugin was introduced in collectd 5.5.

### CODE REVIEW

**Comment by igalic** [comment]
shouldn't we fail, or `warn()` from within the manifest, rather than ignore this option in the template?

**Comment by ffrank** [comment]
If we `warn` (with which I would be happy), we will also want to `notify { "...": loglevel => "warning" }` (or is that "warn" as well?)

We actually want the `notify` more, for that will definitely show up in reports.

**Comment by igalic** [comment]
do elaborate, please.

**Comment by ffrank** [comment]
Invoking the `warn` function on the master will leave a Warning level message in the master log. I'm not sure whether reporting reflects that. I would assume not, since the agent is responsible for compiling the report after its run.

On the other hand, you can do this:

    notify { 'You are doing something insensible':
      loglevel => 'warning',
    }

This shows up in a terrible color on the console when running interactive, and it *will* light up the reports. (I did manage to look up the available [levels](https://docs.puppetlabs.com/references/latest/metaparameter.html#loglevel) by now.)

**Comment by igalic** [comment]
ack, thanks for the clarification.

**Comment by jyaworski** [comment]
Thanks for your contribution!

@igalic why is PCCI voting failing on a lot of PRs?

**Comment by jyaworski** [comment]
I'm going to make an executive decision and merge this.

Thanks!

**Pull request merged**
