### PR TITLE
Add parameter Batch to write_riemann plugin

### PR DESCRIPTION
**Pull request by archii**

### CODE REVIEW

**Comment by jyaworski** [comment]
Tests are failing. Can you try rebasing against the current master?

**Comment by jyaworski** [comment]
Ping @archii

**Comment by archii** [comment]
Sorry for the late response.  I rebased this against master and the checks have all passed now.

**Comment by jyaworski** [comment]
@archii can you squash? 75 commits is kind of difficult to merge.

**Comment by archii** [comment]
@jyaworski all done.

**Pull request merged**
