### PR TITLE
Update from voxpupuli modulesync_config

### PR DESCRIPTION
**Pull request by jyaworski**

### CODE REVIEW

**Comment by jyaworski** [comment]
Calling ruby experts @rnelson0 and @igalic.

**Comment by jyaworski** [comment]
Looks like here:

https://stackoverflow.com/questions/32962161/rspec-given-error-then-is-not-available-from-within-an-example-e-g-an-it-b

**Comment by jyaworski** [comment]
Do we need tmpfilename here?

**Comment by rnelson0** [comment]
It looks like the remove of `spec/spec_helper.rb` line 4 removed that method. I always use `:concat_basedir => '/dne',` (dne == 'does not exist') as it's building the catalog, not actually implementing it, so I think that's probably the best way forward.

**Comment by jyaworski** [comment]
@rnelson0 done.

**Comment by rnelson0** [comment]
Awesome, all tests pass now!

**Pull request merged**
