### PR TITLE
Run beaker tests on all supported & available docker sets

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by bastelfreak** [comment]
three jobs were failed. I restarted them

**Comment by bastelfreak** [comment]
@ekohl we're down to one real error on centos6.  can you please rebase and drop debian7? It got removed from the metadata.json.

**Comment by bastelfreak** [comment]
@ekohl can you please rebase?

**Comment by ekohl** [comment]
Rebased

**Comment by bastelfreak** [comment]
hrm centos6 doesn't like us :(

**Comment by ekohl** [comment]
It looks like it's genuine problem. https://koji.fedoraproject.org/koji/buildinfo?buildID=880588 doesn't list curl_json even though the changelog mentions it should be present.

**Comment by bastelfreak** [comment]
It's not our fault \o/

**Pull request closed without merging**
