### PR TITLE
bump version on puppetlabs/apt dependency

### PR DESCRIPTION
**Pull request by costela**
This seems to require no changes on collectd's side.

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @costela, thansk for the PR! The commit message is a bit missleading. Why do you change the concat dependency as well?

**Comment by costela** [comment]
@bastelfreak oops, that slipped in. Should be clean now.

**Comment by wyardley** [comment]
btw, I think apt is supposed to be a soft dependency per https://docs.puppet.com/puppet/5.1/style_guide.html#dependencies

**Comment by costela** [comment]
@wyardley good point.

**Pull request merged**
