### PR TITLE
This is a test, do not merge

### PR DESCRIPTION
**Pull request by mrunge**
The tests in https://github.com/voxpupuli/puppet-collectd/pull/853
fail, and I can not see the failure connected to the change.

### CODE REVIEW

**Comment by alexjfisher** [comment]
A new version of beaker-puppet was released and it's broken.
Hopefully the fix will be released soon.
https://github.com/puppetlabs/beaker-puppet/pull/68

**Comment by bastelfreak** [comment]
The fix has been merged to beaker-puppet and a new release is out.

**Comment by alexjfisher** [comment]
@bastelfreak Tests are still failing, but for a different reason.  This could be a separate regression?

**Comment by alexjfisher** [comment]
In ...
https://github.com/voxpupuli/puppet-collectd/blob/26b27a8ade0ca5e4a916f41796e42a2c44e3be18/spec/acceptance/curl_json_spec.rb#L38-L40

`curl_json_package` is nil

**Pull request closed without merging**
