### PR TITLE
"Enable testmode switcher"

### PR DESCRIPTION
**Pull request by nibalizer**

### CODE REVIEW

**Comment by igalic** [comment]
"would you mind changing your commit message"

I'd also appreciate an explanation what the motivation here is.
and finally: you do realize this will be overwritten next time someone does a modulesync, right? ;)

**Comment by jyaworski** [comment]
I believe there is a facility in modulesync_config to add new gems. As for the class spec, I'm not sure.

**Comment by juniorsysadmin** [comment]
Does this PR force Beaker testing to be done locally, even if say one might want to run the tests on docker, vms etc?

**Comment by jyaworski** [comment]
@nibalizer is this something we should do across all of our modules?

**Comment by nibalizer** [comment]
This was an experiment. The experiment has failed.

**Pull request closed without merging**
