### PR TITLE
Addition of uuid plugin

### PR DESCRIPTION
**Pull request by crimpy88**

### CODE REVIEW

**Comment by crimpy88** [comment]
Build failing due to errors in : spec/defines/collectd_plugin_snmp_data_spec.rb
Errors fixed in PR https://github.com/voxpupuli/puppet-collectd/pull/562
Re-run of tests after it is merged should see this passing.

**Comment by jyaworski** [comment]
@crimpy88 LGTM minus a few rubocop errors.

**Comment by crimpy88** [comment]
@jyaworski Awesome!
The rubocop errors are coming from changes not made by me. I have however fixed the errors in PR https://github.com/voxpupuli/puppet-collectd/pull/562
https://github.com/voxpupuli/puppet-collectd/pull/562 will need to be merged first, and then this one.

**Comment by bastelfreak** [comment]
@crimpy88 thanks for the PR. Can you rebase (please don't merge master)? Then travis should be happy again.

**Comment by crimpy88** [comment]
@bastelfreak - Done. Travis seems to be in a good mood again.

**Comment by bastelfreak** [comment]
Thanks!

**Pull request merged**
