### PR TITLE
Update fixtures

### PR DESCRIPTION
**Pull request by petems**
* Make sure we're specifying versions from metadata

### CODE REVIEW

**Comment by bastelfreak** [comment]
mhm, I'm not sure if we want that. In general we try to test against master to detect unreleased issues in our dependcies. This revealed several stdlib issues that I'm aware of and probably more. On the negative site we never know if our dependencies in metadata.json are working with the module or if they are outdated.

I would still prefer option 1 for all the unit tests. We can do real testing if correct dependencies in our acceptance tests.

**Comment by juniorsysadmin** [comment]
If we're pinning minimum versions in fixtures, we should also state a minimum version for any soft dependencies in the README

**Comment by juniorsysadmin** [comment]
I'd rather we didn't pin at all in fixtures

**Comment by petems** [comment]
Ok, withdrawn 👍

**Pull request closed without merging**
