### PR TITLE
Fix wrong closure of Host parameter for curljson template

### PR DESCRIPTION
**Pull request by kazeborja**
Configuration file right now is being created with a wrong format since for the Host parameter there is an extra ">"

### CODE REVIEW

**Comment by kazeborja** [comment]
Seems there are some problems with the CI?

**Comment by bastelfreak** [comment]
@kazeborja we fixed that in master. can you please rebase?

**Comment by kazeborja** [comment]
@bastelfreak Done ;)

**Comment by bastelfreak** [comment]
Thanks!

**Pull request merged**
