### PR TITLE
ensure same version as collectd

### PR DESCRIPTION
**Pull request by markasammut**

### CODE REVIEW

**Comment by bastelfreak** [comment]
@markasammut thanks for the PR! Can you take a look at the failing tests?

You can always join us in #voxpupuli on freenode (IRC) if you've any questions about testing.

**Comment by juniorsysadmin** [comment]
@markasammut It would be great if there was a full Pull Request description describing what you are attempting to do and what it fixes

**Comment by markasammut** [comment]
This is the same issue as #550  and #551

**Comment by markasammut** [comment]
As things stand, if you specify a version which is not the latest for collectd, a conflict will be created if a plugin like curl is added. This is because curl will try to be installed with the latest version (and nowhere in the manifest does it instruct it to use the same version as collectd). Subsequent puppet runs will fail as there's an rpm dependency between collectd and the plugins, and collectd will have been updated to the latest package and unable to be downgraded due to a conflict with the plugin's latest version.

This pull request attempts to instruct the plugin to use the same version as collectd if ensure=present.

**Comment by markasammut** [comment]
Can this be re-tested now?

**Comment by bastelfreak** [comment]
Hi @markasammut, your branch has a merge conflict. Can you rebase against our latest master (rebase, not merge)? Feel free to ping us on the freenode IRC channel #voxpupuli if you need any help with git or testing.

**Comment by bastelfreak** [comment]
Thanks for bringing up this PR. I'm going to close this because of inactivity. Please reopen it if you're still interested in it.

**Pull request closed without merging**
