### PR TITLE
added manifest and template to support smart plugin

### PR DESCRIPTION
**Pull request by devfaz**
Hi,

just wrote a small smart-plugin.

 Fabian

### CODE REVIEW

**Comment by ffrank** [comment]
That looks neat, thanks.

Please take note of the [discussion](https://github.com/puppet-community/puppet-collectd/pull/358#issuecomment-150177836) that is currently going on over in #358. We may want to manage this kind of external plugin outside of this module in the future.

**Comment by igalic** [comment]
@ffrank i think we should post $discussion on $mailinglist.

**Comment by blkperl** [comment]
Hi, Thanks for the contribution
 
Please add docs to the README and spec tests.

Also I noticed their are no docs on the official wiki, if you know how to configure the plugin you may want to contribute to the wiki: https://collectd.org/wiki/index.php/Plugin:smart

**Comment by daenney** [comment]
The smart plugin is part of collectd since 5.5, it's not an external plugin so that discussion doesn't really apply.

https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_smart

**Comment by ffrank** [comment]
D'oh, if I could have been bothered to actually look at the change, I would have noticed that it does not in fact include collectd plugin code.

Thanks @daenney. Also +1 to what @blkperl says above. @devfaz if you need help with tests or docs, please let us know.

**Comment by blkperl** [comment]
Closing due to lack of activity. Please reopen when the feedback has been addressed

**Pull request closed without merging**
