### PR TITLE
Support for ethstat plugin

### PR DESCRIPTION
**Pull request by gringus**

### CODE REVIEW

**Comment by jyaworski** [comment]
Thanks for the contribution.

Can we get a test for this?

**Comment by gringus** [comment]
Just added it.

**Comment by jyaworski** [comment]
Rubocop is failing on your test. Try running

```shell
rubocop -a
````

a couple of times. Also, can you squash your commits?

**Comment by gringus** [comment]
Everything has been squashed into 1 commit and now it passes all checks..

$ rubocop -a
Error: The `Style/TrailingComma` cop no longer exists. Please use `Style/TrailingCommaInLiteral` and/or `Style/TrailingCommaInArguments` instead.
(configuration found in /var/tmp/puppet-collectd/.rubocop.yml)

**Comment by jyaworski** [comment]
LGTM.

**Pull request merged**
