### PR TITLE
release 6.0.0

### PR DESCRIPTION
**Pull request by bastelfreak**
This CHANGELOG.md was generated by the github changelog generator. Can someone please review it?

### CODE REVIEW

**Comment by alexjfisher** [comment]
I'd prefer the historic changelog entries were preserved.  https://github.com/skywinder/github-changelog-generator#migrating-from-a-manual-changelog

**Comment by bastelfreak** [comment]
Hi. Do we really want to keep the old, hand written entries if the generator can create them as well? This brings us a unified format with proper links to all the issues and PRs.

I agree with keeping the handcrafted entries if the generator fails, this happens sometimes for past releases (like the 0.0.1 in this case).

**Comment by bastelfreak** [comment]
hold of merging until https://github.com/voxpupuli/puppet-collectd/pull/604 is merged as well.

**Comment by alexjfisher** [comment]
In this module, the old changelog has been very well maintained with 'bugs', 'breaking changes', 'enhancements' etc all carefully documented.  IMO Replacing this with autogenerated noise would be a travesty.

**Pull request closed without merging**
