### PR TITLE
Changes RedHat repo to use the EPEL module

### PR DESCRIPTION
**Pull request by petems**
Installing the RPM is clunky and 99% of people use the EPEL module

### CODE REVIEW

**Comment by petems** [comment]
Need to update metadata also...

**Comment by xaque208** [comment]
+1

**Comment by juniorsysadmin** [comment]
I know this is simply following the pattern, but this is a soft dependency, no?

**Comment by juniorsysadmin** [comment]
I don't like the use of ```require```. Can we avoid it?
Perhaps also consider ```$repo_class``` as a variable

**Comment by vinzent** [comment]
>I don't like the use of ```require```. Can we avoid it?
>Perhaps also consider ```$repo_class``` as a variable

Or just make it completly optional by requiring users to include a repo subclass if they require it? Somewhat Roles/profiles style.

**Comment by petems** [comment]
I was trying to match the original behaviour as much as possible, which is to default to have the upstream class enabled.

**Comment by bastelfreak** [comment]
@petems can you rebase? Then rubocop should be happy again.

**Comment by petems** [comment]
@bastelfreak Done! 👍

**Comment by bastelfreak** [comment]
hrm damn, the recently merged cuda plugin uses the yum module as well.

**Comment by petems** [comment]
@bastelfreak Ah, fixed. 

That's repeated code that could probably be DRY-ed up, but I'll leave that to a seperate PR! :

**Comment by bastelfreak** [comment]
thanks!

**Pull request merged**
