### PR TITLE
fixes #901 by excluding the ReportRelative option

### LINKED ISSUE #901: Error with Plugin "Load" with collectd-5.9 and RHEL-8
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.17
- Ruby:
- Distribution: Red Hat Enterprise Linux release 8.1 (Ootpa)
- Module version: puppet-collectd (v10.1.0)
- Collectd: 5.9.0

## How to reproduce (e.g Puppet code you use)
```
class { 'collectd::plugin::load': }
```

## What are you seeing

Try test config after puppet run.
```
# collectd -T
Error: Parsing the config file failed!
```

## What behaviour did you expect instead
Disable template load.conf.erb for collectd 5.9
https://github.com/voxpupuli/puppet-collectd/blob/master/templates/plugin/load.conf.erb

It works after comment `<Plugin load>` sections in config.
```
# vim /etc/collectd.d/10-load.conf
###### /etc/collectd.d/10-load.conf ###### 
# Generated by Puppet
<LoadPlugin load>
  Globals false
</LoadPlugin>

#<Plugin load>
#  ReportRelative false
#</Plugin>
###### /etc/collectd.d/10-load.conf ###### 

# collectd -T
# systemctl restart collectd
# systemctl status collectd |grep ac
   Active: active (running) since Thu 2019-12-26 16:12:41 MSK; 6s ago
```

## Output log
```
# puppet agent -t
Info: Using configured environment 'develop'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Applying configuration version '1577365409'
Info: Computing checksum on file /etc/collectd.d/.10-load.conf.swp
Info: /Stage[main]/Collectd::Config/File[/etc/collectd.d/.10-load.conf.swp]: Filebucketed /etc/collectd.d/.10-load.conf.swp to puppet with sum fc107359032900b1f7da7d76b871eeb8
Notice: /Stage[main]/Collectd::Config/File[/etc/collectd.d/.10-load.conf.swp]/ensure: removed (corrective)
Info: Class[Collectd::Config]: Scheduling refresh of Class[Collectd::Service]
Info: Class[Collectd::Service]: Scheduling refresh of Service[collectd]
Notice: /Stage[main]/Qas/Exec[vastool_timesync]/returns: executed successfully (corrective)
Notice: /Stage[main]/Collectd::Plugin::Load/Collectd::Plugin[load]/File[load.load]/content: 
--- /etc/collectd.d/10-load.conf        2019-12-26 15:35:50.519697413 +0300
+++ /tmp/puppet-file20191226-32658-5tkooe       2019-12-26 16:03:40.930111466 +0300
@@ -3,6 +3,7 @@
   Globals false
 </LoadPlugin>
 
-#<Plugin load>
-#  ReportRelative false
-#</Plugin>
+<Plugin load>
+  ReportRelative false
+</Plugin>
+

Info: Computing checksum on file /etc/collectd.d/10-load.conf
Info: /Stage[main]/Collectd::Plugin::Load/Collectd::Plugin[load]/File[load.load]: Filebucketed /etc/collectd.d/10-load.conf to puppet with sum 9eecb76e10471d29c19643e62b8c98f2
Notice: /Stage[main]/Collectd::Plugin::Load/Collectd::Plugin[load]/File[load.load]/content: content changed '{md5}9eecb76e10471d29c19643e62b8c98f2' to '{md5}98cd4523a355f4ea6a49c381408380e3'
Notice: /Stage[main]/Collectd::Plugin::Load/Collectd::Plugin[load]/File[load.load]/mode: mode changed '0644' to '0640'
Notice: /Stage[main]/Collectd::Plugin::Load/Collectd::Plugin[load]/File[load.load]/seluser: seluser changed 'unconfined_u' to 'system_u'
Info: /Stage[main]/Collectd::Plugin::Load/Collectd::Plugin[load]/File[load.load]: Scheduling refresh of Service[collectd]
Info: /Stage[main]/Collectd::Plugin::Load/Collectd::Plugin[load]/File[load.load]: Scheduling refresh of Service[collectd]
Info: /Stage[main]/Collectd::Plugin::Load/Collectd::Plugin[load]/File[load.load]: Scheduling refresh of Service[collectd]
Error: /Stage[main]/Collectd::Service/Service[collectd]: Failed to call refresh: Systemd restart for collectd failed!
journalctl log for collectd:
-- Logs begin at Wed 2019-12-04 18:04:43 MSK, end at Thu 2019-12-26 16:03:41 MSK. --
Dec 26 16:03:41  systemd[1]: Stopping Collectd statistics daemon...
Dec 26 16:03:41 systemd[1]: Stopped Collectd statistics daemon.
Dec 26 16:03:41 systemd[1]: Starting Collectd statistics daemon...
Dec 26 16:03:41 collectd[637]: plugin_load: plugin "syslog" successfully loaded.
Dec 26 16:03:41collectd[637]: network plugin: The `MaxPacketSize' must be between 1024 and 65535.
Dec 26 16:03:41 collectd[637]: Error: Parsing the config file failed!
Dec 26 16:03:41 systemd[1]: collectd.service: Main process exited, code=exited, status=1/FAILURE
Dec 26 16:03:41 systemd[1]: collectd.service: Failed with result 'exit-code'.
Dec 26 16:03:41 systemd[1]: Failed to start Collectd statistics daemon.

Error: /Stage[main]/Collectd::Service/Service[collectd]: Systemd restart for collectd failed!
journalctl log for collectd:
-- Logs begin at Wed 2019-12-04 18:04:43 MSK, end at Thu 2019-12-26 16:03:41 MSK. --
Dec 26 16:03:41systemd[1]: Stopping Collectd statistics daemon...
Dec 26 16:03:41 systemd[1]: Stopped Collectd statistics daemon.
Dec 26 16:03:41 systemd[1]: Starting Collectd statistics daemon...
Dec 26 16:03:41 collectd[637]: plugin_load: plugin "syslog" successfully loaded.
Dec 26 16:03:41 collectd[637]: network plugin: The `MaxPacketSize' must be between 1024 and 65535.
Dec 26 16:03:41collectd[637]: Error: Parsing the config file failed!
Dec 26 16:03:41 systemd[1]: collectd.service: Main process exited, code=exited, status=1/FAILURE
Dec 26 16:03:41systemd[1]: collectd.service: Failed with result 'exit-code'.
Dec 26 16:03:41systemd[1]: Failed to start Collectd statistics daemon.

Info: Class[Collectd]: Unscheduling all events on Class[Collectd]
Info: Stage[main]: Unscheduling all events on Stage[main]
Notice: Applied catalog in 7.51 seconds
```

### PR DESCRIPTION
**Pull request by cyberkov**
#### Pull Request (PR) description
If the collectd version is 5.9.0, the `ReportRelative` option is not properly parsed. This unfortunately breaks the module on RedHat 8.1.

#### This Pull Request (PR) fixes the following issues
Fixes #901

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @cyberkov, thanks for the PR. I rebased your code and merged it at https://github.com/voxpupuli/puppet-collectd/pull/907. Are you using the module on RHEL? Can you add Centos 8 / RHEL 8 to the metadata.json file?

**Comment by cyberkov** [comment]
Hi! Thanks a lot. Sure. I'll take care of it, probably on monday when I'm back in the office :-)

**Comment by cyberkov** [comment]
Hello @bastelfreak!
I added RedHat 8 to the metadata but I wasn't sure whether it is necessary to add it to any spectests. The failing tests don't seem to be related to my change, but I am confident that the test in `spec/classes/collectd_plugin_load_spec.rb` will fail sooner or later.
Should I cover that case specifically or is this a thing that'll be covered some other time? :)

Thanks Hannes

**Comment by bastelfreak** [comment]
The failing test was caused by a timeout on the docker daemon. I restarted the test. please have a look at `spec/spec_helper_methods.rb`. It contains two arrays with `7` as version number for CentOS, please update it as well:

```patch
diff --git a/spec/spec_helper_methods.rb b/spec/spec_helper_methods.rb
index ffbb578..0cdd12a 100644
--- a/spec/spec_helper_methods.rb
+++ b/spec/spec_helper_methods.rb
@@ -24,7 +24,7 @@ def all_supported_os_hash
       },
       {
         'operatingsystem' => 'CentOS',
-        'operatingsystemrelease' => ['7']
+        'operatingsystemrelease' => ['7', '8']
       },
       {
         'operatingsystem' => 'Ubuntu',
@@ -46,7 +46,7 @@ def baseline_os_hash
     supported_os: [
       {
         'operatingsystem' => 'CentOS',
-        'operatingsystemrelease' => ['7']
+        'operatingsystemrelease' => ['7', '8']
       }
     ]
   }
```

Also please feel free to enhance as many test files as you like :)

**Comment by bastelfreak** [comment]
ping @cyberkov :)

**Comment by cyberkov** [comment]
> 
> 
> ping @cyberkov :)

Hi!

Sorry I got distracted by recent events (I am in Austria) :)
I'll try to fix it as soon as I have enough time.

Cheers Hannes

**Pull request closed without merging**
