### PR TITLE
add password parameter to redis plugin

### PR DESCRIPTION
**Pull request by sp-joseluis-ledesma**

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi, thanks for the PR. Do you think you can add a spec test for the change?

**Comment by sp-joseluis-ledesma** [comment]
Hi,

   I have added a spec test :)

regards,

**Comment by bastelfreak** [comment]
thanks, the spec tests look good. Can you take a look at the rubocop issues? Then it is ready to merge.

**Comment by sp-joseluis-ledesma** [comment]
solved ;)

**Comment by bastelfreak** [comment]
thanks \o/

**Pull request merged**
