### PR TITLE
update version for collectd package

### PR DESCRIPTION
**Pull request by vaclandic**

### CODE REVIEW

**Comment by bastelfreak** [comment]
Thanks for the PR @vaclandic! The Pattern is getting quite long. Could you please put it into its own datatype? We already have a few in https://github.com/voxpupuli/puppet-collectd/tree/master/types

**Comment by vaclandic** [comment]
@bastelfreak Complete. Could you check please.

**Comment by bastelfreak** [comment]
@vaclandic can you check the used author name/email address in the last commit? The email address isn't associated with your github account.

**Comment by vaclandic** [comment]
@bastelfreak Sorry. Complete

**Comment by bastelfreak** [comment]
Thanks!

**Pull request merged**
