### PR TITLE
Add tests for the AMQP plugin and fix broken StoreRates configuration when amqpformat = JSON

### PR DESCRIPTION
**Pull request by oranenj**
I wrote some tests and caught a bug, it seems.

Not much to say other than that. These tests aren't complete, but they're something.

### CODE REVIEW

**Comment by oranenj** [comment]
... And rebased by temporary commits.

**Comment by bastelfreak** [comment]
Hi @oranenj, thanks for the PR! Travis is a bit buggy right now, I'm looking into this. Can you check the used email address in your commits? The address isn't associated with your github account.

**Comment by oranenj** [comment]
Blaargh, again? I thought I changed my default gitconfig.

**Comment by bastelfreak** [comment]
@oranenj can you take a look at the rubocop errors?

**Comment by oranenj** [comment]
@bastelfreak of course I forgot that. Ran it and rebased...

**Comment by oranenj** [comment]
Uh, the test failure is not showing me any red, and the output from parallel tests is extremely confusing... I think it's this part that caused the failure:
```
Coverage report sent to Coveralls.

    Will create /etc/collectd.d/network-server-node1.conf for collectd >= 4.7

  :ensure => absent

/home/travis/build/voxpupuli/puppet-collectd/vendor/bundle/ruby/2.1.0/gems/json_pure-1.8.6/lib/json/common.rb:155:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)

	from /home/travis/build/voxpupuli/puppet-collectd/vendor/bundle/ruby/2.1.0/gems/json_pure-1.8.6/lib/json/common.rb:155:in `new'

	from /home/travis/build/voxpupuli/puppet-collectd/vendor/bundle/ruby/2.1.0/gems/json_pure-1.8.6/lib/json/common.rb:155:in `parse'

	from /home/travis/build/voxpupuli/puppet-collectd/vendor/bundle/ruby/2.1.0/gems/simplecov-0.12.0/lib/simplecov/last_run.rb:12:in `read'

	from /home/travis/build/voxpupuli/puppet-collectd/vendor/bundle/ruby/2.1.0/gems/simplecov-0.12.0/lib/simplecov/defaults.rb:80:in `block in <top (required)>'

      Will not create 10-amqp.conf
```

**Comment by oranenj** [comment]
Hmm, locally I get this:
```
python_dir
  is empty string if python not installed
  python dir
    default path
      example at ./spec/unit/python_dir_spec.rb:12 (FAILED - 1)
    RedHat
      should eq "/usr/lib/python2.7/site-packages"
```

**Comment by oranenj** [comment]
```
  1) python_dir python dir default path 
     Failure/Error: Facter::Util::Resolution.exec('python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"')
     
     Mocha::ExpectationError:
       unexpected invocation: Facter::Util::Resolution.exec('python -c \'from distutils.sysconfig import get_python_lib; print(get_python_lib())\'')

```
Hmm

**Comment by oranenj** [comment]
All tests pass for me locally now. If they still fail on travis, something else is going on.

**Comment by bastelfreak** [comment]
Thanks!

**Pull request merged**
