### PR TITLE
OpenBSD Support

### PR DESCRIPTION
**Pull request by xaque208**

### CODE REVIEW

**Comment by xaque208** [comment]
A test has been added.  Thank you.

**Comment by xaque208** [comment]
The test failure *still* looks unrelated to my change.

**Comment by jyaworski** [comment]
LGTM. Merging despite.

**Comment by xaque208** [comment]
Thank you.

**Comment by xaque208** [comment]
@jyaworski Is there any chance this could get a release?

**Comment by jyaworski** [comment]
@xaque208 could you file an issue for a new release?

**Pull request merged**
