### PR TITLE
Add ExcludeRegex option to tail module

### PR DESCRIPTION
**Pull request by matejzero**
Tail plugin has an option to also set ExcludeRegex.

I tried adding a test as well, but I'm having some troubles. Will try some more and commit when I'll have something useful.
I also can't find a good case for documentation.

### CODE REVIEW

**Comment by jyaworski** [comment]
Hello @matejzero.

Do you know in what version this was added? If so, please wrap the line in a version conditional.

**Comment by matejzero** [comment]
It was added in 4.10.0 and 5.1.0.
I checked supported distros and they all have those versions and newer. Is version check still necessary in that case?

**Comment by igalic** [comment]
i'm okay with this, if you are, @jyaworski

**Comment by matejzero** [comment]
Great! Thanks for merge.

**Pull request merged**
