### PR TITLE
Collectd version fact value

### PR DESCRIPTION
**Pull request by ctriegg**
fixes issue #700

### CODE REVIEW

**Comment by bastelfreak** [comment]
Strange thing here is that our tests were green before this change, so they didn't detect this error. Conclusion: We don't have a test that proves that this change fixes anything / breaks nothing. In theory the puppetlabs_spec_helper enables STRICT_VARIABLES. It needs to be checked if this is actually the case, or if we need more tests here.

**Comment by bastelfreak** [comment]
@ctriegg cna you also please check the used email address in your commit? It isn't associated with your github account.

**Comment by ekohl** [comment]
@bastelfreak we ensure the fact is present in our tests: https://github.com/voxpupuli/puppet-collectd/blob/15a028feb63f64444ce837c3f7397c46d219d13e/spec/default_module_facts.yml#L2

**Comment by alexjfisher** [comment]
I'm not sure this is the right fix.  As per our own docs, we shouldn't be using [top scope variables to access facts](https://github.com/voxpupuli/voxpupuli.github.io/blame/master/docs/index.md#L125).

I think changing [init.pp](https://github.com/voxpupuli/puppet-collectd/blob/15a028feb63f64444ce837c3f7397c46d219d13e/manifests/init.pp#L37) line 37
```
collectd_version_real = pick($::collectd_version, $minimum_version)
```
to
```
collectd_version_real = pick_default($facts['collectd_version'], $minimum_version)
```
would be better.

**Comment by alexjfisher** [comment]
Actually, I think this isn't just a style thing.  This PR introduces a bug.
`collectd_version_real` should equal `minimum_version` if the fact isn't available, not `false`.

**Comment by ctriegg** [comment]
alexjfisher is right. 
adapting `pick` to `pick_default` is the better solution. 

just running tests, pushing it when they're finished

**Comment by alexjfisher** [comment]
@ctriegg I've already got https://github.com/voxpupuli/puppet-collectd/pull/708 open (which includes a similar fix for `python_dir`)

**Comment by alexjfisher** [comment]
@ctriegg Thank you for looking into this.

**Pull request closed without merging**
