### PR TITLE
Remove interval parameter from write plugins.

### PR DESCRIPTION
**Pull request by kbor**
Hello, to my knowledge it makes no sense to configure interval for write plugins. Collectd has no concept of interval for write plugins and if configured, it is silently ignored. It is therefore better to remove it from the configuration so that manifests don't give a false impression that this parameter does something useful.

### CODE REVIEW

**Comment by oranenj** [comment]
There seem to be some puppet lint issues. Could you fix those?

**Comment by bastelfreak** [comment]
Hi @kbor, thanks for the PR. Can you please rebase it against latest master?

**Comment by kbor** [comment]
Hi, yes, sorry, didn't notice. Lint fixed and rebased.

**Comment by bastelfreak** [comment]
Thanks!

**Pull request merged**
