### PR TITLE
Genericjmx class path

### PR DESCRIPTION
**Pull request by maage**
I needed to collect metrics from jboss and to do that I needed to add jboss-cli-client.jar to be able to use service::jmx::remote+http://<ip>:<port> type service_url. This would have been possible by redefining class path again, but it is kind of kludgy as then you need to know default class_path. Another way to do this could be to fix current collectd jar files. But for now I think this way should fix most problems.

I've also added another patch to fix indent of generated configuration.

### CODE REVIEW

**Comment by oranenj** [comment]
Looks like metadata lint is broken :(

**Comment by oranenj** [comment]
Acceptance tests are passing and our spec tests are still broken. I think this is okay to merge

**Comment by bastelfreak** [comment]
Hi @maage , thanks for the PR. Can you please rebase it against latest master?

**Comment by oranenj** [comment]
I resolved the conflicts. Can't run tests for some reason.

**Comment by wyardley** [comment]
@oranenj not sure why the one test failed, I kicked it off again in case it was a transient issue.
There's also 2 rubocop warnings `bundle exec rake rubocop`
Even if you don't have the tests working locally, you can see the test output and the items that failed in Travis.

https://travis-ci.org/voxpupuli/puppet-collectd/builds/258536773?utm_source=github_status&utm_medium=notification

**Comment by bastelfreak** [comment]
@maage can you please rebase? We fixed the spec issues in our master branch.

**Comment by bastelfreak** [comment]
I'm going to close this PR. Please reopen it if you're still interested in it.

**Pull request closed without merging**
