### PR TITLE
Fix for issue #552 including acceptance tests

### PR DESCRIPTION
**Pull request by Yuav**
Adding Docker nodesets for
Debian 7/8
Ubuntu 12/14/16
Ommiting CentOS 6/7 due to bug

### CODE REVIEW

**Comment by Yuav** [comment]
Seems Travis needs to retry on Debian

**Comment by Yuav** [comment]
Retrying

**Comment by Yuav** [comment]
Fixes #552 with acceptance tests to prove it

**Comment by daenney** [comment]
This is way way way too many commits. Please do some work to rewrite history in much more processable and contained sets of commits.

Also, the changes to `.travis.yml` might get module synced away.

**Comment by Yuav** [comment]
I did a rebase from master. Not sure why they all ended up in the log

**Comment by daenney** [comment]
I'm not sure the Travis+Docker changes is something we want to do right now. This is going to dramatically slow down tests, it's adding  9 tests to the matrix and Beaker tests are pretty slow in general.

**Comment by Yuav** [comment]
The module was unusable on CentOS 6 and 7 for instance. The added tests would ensure that doesn't happen again

**Comment by Yuav** [comment]
Not sure I agree with "dramatically" though? Spec test on Ruby 2.3.1 is already 4 minutes, which is longer than most of the Beaker tests. In my opinion the Beaker tests have more value than multiple ruby versions

**Comment by daenney** [comment]
It's at worst 9x~3m that get added to the test time when it's busy and things can't get scheduled in parallel, That's almost 20 minutes extra wait time, in practice it's probably around 10m.

**Comment by Yuav** [comment]
In my opinion it's still worth it :-)

**Comment by bastelfreak** [comment]
IMO we should wait with the acceptance test until https://github.com/voxpupuli/modulesync_config/pull/230 is resolved. Maybe it is a good idea to add the tests from this PR in a new one?

**Comment by daenney** [comment]
The adding and revert should be squashed to just eliminate them from history.

**Pull request merged**
