### PR TITLE
[WIP]Testplatforms

### PR DESCRIPTION
**Pull request by bastelfreak**
Just a test for if the platforms settings really works. please don't merge.

CC @jyaworski

### CODE REVIEW

**Comment by bastelfreak** [comment]
The correct version is specified [here](http://bundler.io/v1.11/man/gemfile.5.html). In my opinion the gem line is correct, but it still installs it on all platforms. Maybe some problems with our groups?

**Comment by bastelfreak** [comment]
okay, no clue why this doesn't work.

**Comment by jyaworski** [comment]
```ruby
install_if -> { Gem::Version.new(RUBY_VERSION) > Gem::Version.new('2.0.0') } do
  gem 'listen', '~> 3.0.0', :require => false
end
```

**Comment by jyaworski** [comment]
We should gem update bundler in before_install....

**Comment by jyaworski** [comment]
https://docs.travis-ci.com/user/languages/ruby#Upgrading-RubyGems

**Comment by bastelfreak** [comment]
wopwop, wörks as intended \o/

**Comment by bastelfreak** [comment]
figuered everything out in modulesync PR 125-130

**Pull request closed without merging**
