### PR TITLE
add AutoLoadPlugin to global options

### PR DESCRIPTION
**Pull request by mrunge**
#### Pull Request (PR) description
This PR adds adding AutoLoadPlugin to global options. Usually, it should be disabled.

### CODE REVIEW

**Comment by paramite** [comment]
Please add following, otherwise +1:

diff --git a/spec/classes/collectd_init_spec.rb b/spec/classes/collectd_init_spec.rb
index 2d598e1..aa36921 100644
--- a/spec/classes/collectd_init_spec.rb
+++ b/spec/classes/collectd_init_spec.rb
@@ -41,6 +41,7 @@ describe 'collectd', type: :class do
         let(:params) { { purge_config: true } }
 
         it { is_expected.to contain_file('collectd.conf').with_content(%r{FQDNLookup true}) }
+        it { is_expected.to contain_file('collectd.conf').with_content(%r{AutoLoadPlugin}) }
         it { is_expected.to contain_file('collectd.conf').with_content(%r{Interval}) }
         it { is_expected.to contain_file('collectd.conf').with_content(%r{Timeout}) }
         it { is_expected.to contain_file('collectd.conf').with_content(%r{ReadThreads}) }

**Comment by mrunge** [comment]
Good suggestion, thank you!

**Comment by bastelfreak** [comment]
Thanks @mrunge !

**Comment by mrunge** [comment]
Thank you @bastelfreak for the quick merge!

**Pull request merged**
