### PR TITLE
Added package managing to the ceph plugin, as well as documentation a…

### PR DESCRIPTION
**Pull request by lilhuang**
Please check the following items before submitting a PR -- thank you!

Note that this project is released with a Contributor Code of Conduct.
By participating in this project you agree to abide by its terms.
[Contributor Code of Conduct](https://voxpupuli.org/coc/).

- [x] There is no existing PR that addresses this problem
- [x] Mentioned any existing issues in your commit so they get linked and
  closed once this PR gets merged, i.e: `Closes #1554` in the body of a commit
- [x] Followed the instructions in the [Contributing](CONTRIBUTING.md) document
- [x] Ran the unit/spec tests and ensured they still pass
- [x] Added tests to cover the new behaviour
- [x] Updated the documentation to match the changes
- [x] When possible, add an entry to the CHANGELOG file
- [x] Squashed your PR down to a single commit. You may forego this if the PR
  tries to address multiple issues. Though we prefer one PR per feature/fix,
  sometimes that's not feasible. In that case ensure that a single feature/fix
  and associated tests and documentation is bundled up in one commit

Optional, but extra points:

- [ ] Added tests to ensure the old behaviour cannot accidentally be
  reintroduced

- - -

…nd an appropriate test

### CODE REVIEW

**Comment by jyaworski** [comment]
@lilhuang can you rebase on the current master, and squash? It looks like rubocop is failing but the rest looks good.

**Comment by jyaworski** [comment]
@lilhuang can you do so again?

**Comment by bastelfreak** [comment]
@lilhuang can you please rebase again?

**Comment by bmeekhof** [comment]
@bastelfreak I've taken over responsibility for this.  Just rebased against current master.  Let me know if you need anything else.

**Comment by ffrank** [comment]
The new tests don't seem to pass, e.g. https://travis-ci.org/voxpupuli/puppet-collectd/jobs/166530897

**Comment by bmeekhof** [comment]
Sorry - did not update spec test to reflect the parameter change recently pulled into master.  Fixed and passes local run of spec tests.

**Comment by bmeekhof** [comment]
Just added one more edit to the spec to define the operatingsystemmajrelease fact.  Spec tests for this plugin pass but there are other modules in the tree which fail the automated checks because the fact is not defined in their spec tests.

**Comment by ffrank** [comment]
Huh? Have we broken those in master?

Thanks @bmeekhof for keeping on top of this.

**Comment by bastelfreak** [comment]
I'm investigating in the tests right now and hit the point where I just want to cry. Maybe I get over it and can provide a fix later. We merged two PRs almost at the same time, the second didn't include changes from the first, which leads to the current fails.

**Comment by crimpy88** [comment]
@bastelfreak - does PR https://github.com/voxpupuli/puppet-collectd/pull/566 not assist with this issue?

**Comment by bastelfreak** [comment]
It does, yeah. I'm currently spinning up another PR which implements rpsec-puppet-facts. This should result in better tests.

**Comment by crimpy88** [comment]
Nice. Hadn't seen that before :-)

**Comment by ffrank** [comment]
Oh, neat. A real-life case of the "well the patches apply cleanly, so" fallacy :)

All the ❤️ and good luck to @bastelfreak!

**Comment by bastelfreak** [comment]
Fixed in https://github.com/voxpupuli/puppet-collectd/pull/566. @lilhuang please rebase after https://github.com/voxpupuli/puppet-collectd/pull/566 got merged.

**Comment by dhoppe** [comment]
@lilhuang I just restarted the TravisCI build. Could you please fix the Rubocop issues?

**Comment by bmeekhof** [comment]
Rebased and Rubocop issue fixed.

**Pull request merged**
