### PR TITLE
Enable acceptance tests

### PR DESCRIPTION
**Pull request by Yuav**

### CODE REVIEW

**Comment by bastelfreak** [comment]
@Yuav are you able to take a look at the failling acceptance test?

**Comment by Yuav** [comment]
Uh. Really strange. Looks like it's not honoring the provider option on CentOS

**Comment by bastelfreak** [comment]
thanks!

**Comment by thlapin** [comment]
Hi, can I ask why 948e3aae0d30b3673f4f0be275906dd03321e959 changed the from RedHat to Fedora? The commit message isn't clear and this is now preventing me from using the manage_package parameter on centos.

**Comment by bastelfreak** [comment]
@thlapin thanks for bringing this up. @Yuav do you know why you changed the fact? The package is available  in the collectd-ci repository for centos as well.

**Comment by Yuav** [comment]
It wasn't available at the time I implemented it

**Comment by bastelfreak** [comment]
@thlapin can you open a new issue and describe the environment you're in and show your profile that calls the collectd class? (or even provide a PR with fixes, if you can)

**Comment by alexjfisher** [comment]
https://github.com/voxpupuli/puppet-collectd/commit/948e3aae0d30b3673f4f0be275906dd03321e959 also seems to contain the change that goes with the commit message from
https://github.com/voxpupuli/puppet-collectd/pull/598/commits/8b30506740a14fee4cb136d14da7e94efa27b7f3
Either way, I think this PR fixes the issue reported in https://github.com/voxpupuli/puppet-collectd/issues/679 ?

**Pull request merged**
