### PR TITLE
templates: Fix version conditionals by using scope['::collectd::collectd_version'] instead of @collectd_version

### PR DESCRIPTION
**Pull request by caldwell**
@collectd_version is always nil due to 29dd796685469b3dc74a973eefca62ac1ed6e27f.

### CODE REVIEW

**Comment by igalic** [comment]
i thought we had fixed that :|

**Comment by jyaworski** [comment]
Hello.

Is this failing build? Can it be looked at?

**Comment by bastelfreak** [comment]
@jyaworski will fix this in [PR393](https://github.com/voxpupuli/puppet-collectd/pull/393). We can close this one if his solution is merged.

**Comment by jyaworski** [comment]
Fixed in #393

**Pull request closed without merging**
