### PR TITLE
add write_kafka support

### PR DESCRIPTION
**Pull request by bnied**
This PR adds support for the [write_kafka](https://collectd.org/wiki/index.php/Plugin:Write_Kafka) plugin.

### CODE REVIEW

**Comment by jyaworski** [comment]
Does this require an external package?

Also, maybe note it's in 5.5+.

**Comment by bnied** [comment]
Yes, this requires `librdkafka1` to be present.

I can note the version requirement; do you want this in the README?

**Comment by jyaworski** [comment]
@bnied yeah, that looks good. I meant, for example, the disk plugin which on RHEL as 'collectd-disk.' External requirements like that can just be noted. It's the same way for Redis.

**Comment by bnied** [comment]
Gotcha. On Ubuntu, the plugin should be included in the collectd or collectd-core packages.

On Fedora/RHEL, the package will be `collectd-write_kafka` (going off of [their official specfile](https://github.com/collectd/collectd/blob/master/contrib/redhat/collectd.spec#L764-L772)), though it appears that neither RHEL/CentOS or Fedora package the library or the write_kafka plugin.

**Comment by bnied** [comment]
@jyaworski added the notes to the README. Is there anything else you need for this PR?

**Comment by bnied** [comment]
Thanks!

**Pull request merged**
