### PR TITLE
add spec tests and update README for write_tsdb plugin

### PR DESCRIPTION
**Pull request by mothbe**

### CODE REVIEW

**Comment by jyaworski** [comment]
@mothbe can you check the spec tests (2.2 and above, for now)?

**Comment by bastelfreak** [comment]
@mothbe for the rubocop issues; rubcop -a should autofix most of them for you.

**Comment by jyaworski** [comment]
@mothbe can you rebase against master and squash? That should make the tests act better. It looks like 2.2+ (where the tests were valid when this was run) fails due to strict_variables.

**Comment by mothbe** [comment]
@jyaworski I can do it.

**Comment by jyaworski** [comment]
@mothbe can you squash?

**Comment by bastelfreak** [comment]
nono :(

please don't squash them into one commit. reviewing and also reverting (if we ever have to do this) of a small commit with a single logical change is always easier. Please check the email/author you used, github can't recognize you. In most cases the people commited with an emaila address that isn't linked to their github profile.

Also please check your second and forth commit, their messages aren't meaningful.

**Comment by jyaworski** [comment]
Commits should not be 'fix' 'blah' etc. They should be distinct pieces of functionality. For example:

https://github.com/virtapi/marmoset/blob/master/CONTRIBUTING.md#make-separate-commits-for-logically-separate-changes

**Comment by mothbe** [comment]
I think, it is better to close this pull request and create new with proper changes.

**Comment by jyaworski** [comment]
@mothbe sure. Just ping me on the new PR.

**Pull request closed without merging**
