### PR TITLE
Adds class ovs_stats plugin

### PR DESCRIPTION
**Pull request by paramite**
This patch is adding support for ovs_stats plugin configuration and installation.

### CODE REVIEW

**Comment by paramite** [comment]
Do you guys have any hint on why checks are failing? I must be blind, but I don't see any reasonable cause. The same is for ovs_events PR.

**Comment by paramite** [comment]
@alexjfisher: Hi, maybe you will know?

**Comment by paramite** [comment]
Can this be merged now please, when all checks are passing?

**Comment by alexjfisher** [comment]
@paramite Sorry for not responding sooner.  Looks really good.  Thanks!

**Comment by paramite** [comment]
No problem, thanks for merging.

**Pull request merged**
