### PR TITLE
Add puppet tasks to call collectdctl

### PR DESCRIPTION
**Pull request by traylenator**
#### Pull Request (PR) description

Two puppet tasks

* collectd::listval - lists all collectd metrics on a node
* collectd::getval metric=load/load-relative - shows values
  of a particular metric

For example

```bash
$ bolt -u root task run collectd::getval metric=load/load-relative -n node.example.org
Started on node.example.org...
Finished on node.example.org:
  {
    "metric": "load/load-relative",
    "values": {
      "shortterm": "1.750000e-01",
      "longterm": "8.000000e-02",
      "midterm": "8.500000e-02"
    }
  }
```

### CODE REVIEW

**Comment by traylenator** [comment]
I added a new dependency to metadata.yaml - I'm easily persuaded this should just be a comment in the README.

**Comment by traylenator** [comment]
There is a massive lack of tests here. Very happy to do some but we need some framework.

**Comment by alexjfisher** [comment]
> I added a new dependency to metadata.yaml - I'm easily persuaded this should just be a comment in the README.

I think it's fine in the metadata.

**Comment by traylenator** [comment]
It's broken on centos6 with python 2.6 . I have a fix migrating to `python3` which is available on 6 also.
Another commit here?

**Pull request merged**
