### PR TITLE
Add support for nut plugin and fix os specific location of typesdb

### PR DESCRIPTION
**Pull request by amishHammer**
Add support for nut plugin and fix os specific location of typesdb.

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @amishHammer, could you please rebase against current master?

**Comment by amishHammer** [comment]
@bastelfreak this should be against the current master.

**Comment by bastelfreak** [comment]
thanks. Can you take a look at the puppet-lint errors?

**Comment by bastelfreak** [comment]
ping @amishHammer

**Comment by bastelfreak** [comment]
Hi @amishHammer. I'm going to close this PR due to inactivity. Please feel free to reopen it if you're still interested.

**Pull request closed without merging**
