### PR TITLE
add support for write_tsdb

### PR DESCRIPTION
**Pull request by mothbe**

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi, thanks for the contribution. Could you also add spec tests please?

**Comment by bastelfreak** [comment]
Please also take a look at the travis issues. There are some alignment issues in your code.

**Comment by jyaworski** [comment]
@mothbe beat me to writing the tsdb plugin. :)

rubocop -a should help.

**Comment by ochykysh** [comment]
@mothbe How about using an array for the host tags? This way one can use the deeper merging in hiera  to set the tags more gradually.

I have it in my branch ochykysh/puppet-collectd.

Or I can open a separate merge request for this

**Comment by mothbe** [comment]
@ochykysh host_tags is an array now .
@bastelfreak  spec tests will be completed soon ...

**Comment by jyaworski** [comment]
I'm looking at several other plugins, and their templates seem to be different than this one. Do you need the loadplugin stanza?

Like here:

https://github.com/voxpupuli/puppet-collectd/blob/master/templates/plugin/java.conf.erb

**Comment by ochykysh** [comment]
@mothbe, please update the README.MD as well, feel free to use a commit from by branch - https://github.com/ochykysh/puppet-collectd/commit/81461f06e59296df69fb5d8cbaff57b13e878c05

@jyaworski the java plugin is a special case, write_tsdb is very simple, like write_sensu..

**Comment by jyaworski** [comment]
@ochykysh would you be willing to update the README as a PR after this is merged?

**Pull request merged**
